DROP DATABASE IF EXISTS CSCI201_HangmanGame_bx;
CREATE DATABASE CSCI201_HangmanGame_bx;
USE CSCI201_HangmanGame_bx;

CREATE TABLE IF NOT EXISTS Users (
		uid SMALLINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
		username VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL UNIQUE,
        password VARCHAR(50) NOT NULL,
        wins INT(3) NOT NULL,
        losses INT(3) NOT NULL
)